"""empty message

Revision ID: 186f231f4cfc
Revises: 8e4109ac0b06
Create Date: 2016-07-14 05:44:44.870710

"""

# revision identifiers, used by Alembic.
revision = '186f231f4cfc'
down_revision = '8e4109ac0b06'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects_hosts',
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects_hosts')
    ### end Alembic commands ###
