"""empty message

Revision ID: 23443bf925a3
Revises: cd4da17b2e10
Create Date: 2016-07-12 07:15:10.266053

"""

# revision identifiers, used by Alembic.
revision = '23443bf925a3'
down_revision = 'cd4da17b2e10'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=30), nullable=True),
    sa.Column('ipaddress', sa.String(length=20), nullable=True),
    sa.Column('az', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname'),
    sa.UniqueConstraint('ipaddress')
    )
    op.add_column(u'projects', sa.Column('host', sa.Integer(), nullable=True))
    op.add_column(u'projects', sa.Column('log_path', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'projects', 'hosts', ['host'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column(u'projects', 'log_path')
    op.drop_column(u'projects', 'host')
    op.drop_table('hosts')
    ### end Alembic commands ###
