"""empty message

Revision ID: 3d76e9857185
Revises: 23443bf925a3
Create Date: 2016-07-13 07:29:09.980637

"""

# revision identifiers, used by Alembic.
revision = '3d76e9857185'
down_revision = '23443bf925a3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin')
    ### end Alembic commands ###
