"""empty message

Revision ID: 70252a1a6444
Revises: 186f231f4cfc
Create Date: 2016-07-15 07:22:30.359792

"""

# revision identifiers, used by Alembic.
revision = '70252a1a6444'
down_revision = '186f231f4cfc'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects_hosts')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects_hosts',
    sa.Column('host_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['host_id'], [u'hosts.id'], name=u'projects_hosts_ibfk_1'),
    sa.ForeignKeyConstraint(['project_id'], [u'projects.project_id'], name=u'projects_hosts_ibfk_2'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
