"""empty message

Revision ID: 8e4109ac0b06
Revises: 3d76e9857185
Create Date: 2016-07-14 05:06:09.286294

"""

# revision identifiers, used by Alembic.
revision = '8e4109ac0b06'
down_revision = '3d76e9857185'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('host_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'projects_ibfk_1', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'hosts', ['host_id'], ['id'])
    op.drop_column('projects', 'host')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('host', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(u'projects_ibfk_1', 'projects', 'hosts', ['host'], ['id'])
    op.drop_column('projects', 'host_id')
    ### end Alembic commands ###
