"""empty message

Revision ID: cd4da17b2e10
Revises: de64b61ddfdb
Create Date: 2016-07-11 10:55:24.050803

"""

# revision identifiers, used by Alembic.
revision = 'cd4da17b2e10'
down_revision = 'de64b61ddfdb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['project_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'project_id')
    ### end Alembic commands ###
