"""empty message

Revision ID: de64b61ddfdb
Revises: e98a72bd9a9d
Create Date: 2016-07-11 10:44:03.786928

"""

# revision identifiers, used by Alembic.
revision = 'de64b61ddfdb'
down_revision = 'e98a72bd9a9d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    ### end Alembic commands ###
